---
name: elasticsearch
logging: 
   level: debug
director_uuid: 1d96c6c8-8d70-4a09-b6cb-dcba916fa5c3
release:
  name: elasticsearch
  version: latest

compilation:
  workers: 2
  network: default
  cloud_properties:
    instance_type: m1.small
  reuse_compilation_vms: true

update:
  canaries: 1
  canary_watch_time: 30000 - 240000
  update_watch_time: 30000 - 600000
  max_in_flight: 2

resource_pools:
 - name: infrastructure1
   network: default
   size: 2
   stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
   cloud_properties:
    instance_type: m1.small

networks:
- name: floating
  type: vip
  cloud_properties: {}
- name: default
  type: dynamic
  cloud_properties:
    security_groups: ['bosh']
    subnet: subnet-ef966498
    region: us-east-1
    
    
jobs: 
 - name: elasticsearch
   templates:
   - name :  elasticsearch
   instances: 2
   resource_pool: infrastructure1
   persistent_disk: 20000
   networks:
   - name: default
