#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/elasticsearch
LOG_DIR=/var/vcap/sys/log/elasticsearch
PIDFILE=${RUN_DIR}/pid
BIN_DIR=/var/vcap/packages/elasticsearch/bin

export JAVA_HOME=/var/vcap/packages/jdk
export PATH=$PATH:$JAVA_HOME/bin:$BIN_DIR

#source /var/vcap/packages/common/utils.sh

case $1 in 
  start)
    mkdir -p $RUN_DIR 
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $RUN_DIR 
    chwon -R vcap:vcap $LOG_DIR
	${BIN_DIR}/elasticsearch  -p $PIDFILE	
	;;
	
  stop)
    kill -9 `cat $PIDFILE`

	rm -f $PIDFILE
	;;
	
  *)
	echo "Usage: elasticsearch -d -p PIDFILE"
	
	;;

esac	
